services:
  - type: web
    name: ai-resume-analyser
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run shortlister3.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
